backend/controllers/PostController.php
<?php

namespace backend\controllers;

use backend\models\search\SponsorsPostSearch;
use common\helpers\ColumnVisible;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;

/**
 * PaymentsSales controller
 */
class PostController extends Controller
{

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => ['index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Страница отображения списка продаж
     *
     * @return string
     */
    public function actionIndex()
    {
        $filter = ColumnVisible::getColumnVisible('sponsor_post', [
            'sponsor_id' => 'on',
            'post_date' => 'on',
            'status' => 'on',
            'assign_sponsor_id' => 'on',
            'post' => 'on',
        ]);
        $searchModel = new SponsorsPostSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
            'filter' => $filter,
            'per_page' => Yii::$app->request->get('per-page', 20),
        ]);
    }

}

backend/controllers/SponsorsController.php
<?php

namespace backend\controllers;

use backend\models\search\SponsorOrderReviewSearch;
use backend\models\search\SponsorPromoSearch;
use backend\models\search\SponsorsAccessSearch;
use backend\models\search\SponsorsBacklinksSearch;
use backend\models\search\SponsorsPaymentsHistorySearch;
use backend\models\search\SponsorsPaymentsMethodSearch;
use backend\models\search\SponsorsPaymentsProgramsSearch;
use backend\models\search\SponsorsPaymentsSalesSearch;
use backend\models\search\SponsorsPostSearch;
use backend\models\search\SponsorsReviewSearch;
use backend\models\search\SponsorsSearch;
use backend\models\search\SponsorsSitesSearch;
use backend\models\search\SponsorsSupportSearch;
use common\helpers\ColumnVisible;
use common\models\entity\SponsorAccess;
use common\models\entity\SponsorBacklinks;
use common\models\entity\SponsorOrderReview;
use common\models\entity\SponsorPaymentsHistory;
use common\models\entity\SponsorPaymentsMethod;
use common\models\entity\SponsorPaymentsProgram;
use common\models\entity\SponsorPaymentsSales;
use common\models\entity\SponsorPost;
use common\models\entity\SponsorPromo;
use common\models\entity\Sponsors;
use common\models\entity\SponsorSites;
use common\models\entity\SponsorsReview;
use common\models\entity\SponsorSupport;
use common\models\enums\PaymentsMethodStatus;
use Yii;
use yii\db\StaleObjectException;
use yii\filters\AccessControl;
use yii\helpers\Html;
use yii\web\Controller;
use yii\web\Response;
use yii\web\UploadedFile;

/**
 * Site controller
 */
class SponsorsController extends Controller
{
    private $columnVisible = [
        'name' => 'on',
        'slug' => 'on',
        'ref_url' => 'on',
        'domain' => 'on',
        'description' => 'on',
        'publication_status' => 'on',
        'recommendation_status' => 'on',
        'not_recommendation_reason' => 'on',
        'general_company_id' => 'on',
        'cms_id' => 'on',
        'image' => 'on',
    ];

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => [
                            'index',
                            'create',
                            'update',
                            'delete',
                            'payments-method',
                            'payments-method-create',
                            'payments-method-update',
                            'payments-method-delete',
                            'payments-history',
                            'payments-history-create',
                            'payments-history-update',
                            'payments-history-delete',
                            'payments-programs',
                            'payments-programs-create',
                            'payments-programs-update',
                            'payments-programs-delete',
                            'payments-sales',
                            'payments-sales-create',
                            'payments-sales-update',
                            'payments-sales-delete',
                            'support',
                            'support-create',
                            'support-update',
                            'support-delete',
                            'sites',
                            'sites-create',
                            'sites-update',
                            'sites-delete',
                            'advertising',
                            'post',
                            'post-create',
                            'post-update',
                            'post-delete',
                            'access',
                            'access-create',
                            'access-update',
                            'access-delete',
                            'backlinks',
                            'backlinks-create',
                            'backlinks-update',
                            'backlinks-delete',
                            'review',
                            'review-create',
                            'review-update',
                            'review-delete',
                            'order-review',
                            'order-review-create',
                            'order-review-update',
                            'order-review-delete',
                            'promo',
                            'promo-create',
                            'promo-update',
                            'promo-delete',
                            'save-review-text',
                            'get-sponsor-sites'
                        ],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Страница отображения списка пользователей
     *
     * @return string
     */
    public function actionIndex()
    {
        $filter = ColumnVisible::getColumnVisible('sponsors', $this->columnVisible);
        $searchModel = new SponsorsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
            'filter' => $filter,
            'per_page' => Yii::$app->request->get('per-page', 20),
        ]);
    }

    /**
     * Создание пользователя
     *
     * @return string
     */
    public function actionCreate()
    {
        $model = new Sponsors();
        $model->publication_status = 1;
        if ($model->load(Yii::$app->request->post())) {
            $model->imageFile = UploadedFile::getInstance($model, 'imageFile');
            if ($model->imageFile) {
                $model->imageFile->saveAs("image/payment-system/{$model->imageFile->baseName}.{$model->imageFile->extension}");
                $model->image = "/image/payment-system/{$model->imageFile->baseName}.{$model->imageFile->extension}";
            }
            if ($model->save()) {
                Yii::$app->session->setFlash('success', 'Запись успешно создана');
                if  (Yii::$app->request->get('exit')!=1) {
                    return $this->redirect(['update','id'=>$model->id]);
                } else {
                    return $this->redirect(['index']) ;
                }
            }
            var_dump($model->errors);
        }
        return $this->render('create', ['model' => $model]);
    }

    /**
     * Редактирование спонсора
     *
     * @param $id
     * @return string
     */
    public function actionUpdate($id)
    {
        $model = Sponsors::findOne(intval($id));
        $model->imageFile = $model->image;
        if ($model->load(Yii::$app->request->post())) {
            $model->imageFile = UploadedFile::getInstance($model, 'imageFile');
            if ($model->imageFile) {
                $model->imageFile->saveAs("image/payment-system/{$model->imageFile->baseName}.{$model->imageFile->extension}");
                $model->image = "/image/payment-system/{$model->imageFile->baseName}.{$model->imageFile->extension}";
            }
            if ($model->save()) {
                Yii::$app->session->setFlash('success', 'Запись успешно сохранена');
                if  (Yii::$app->request->get('exit')==1) {
                    return $this->redirect(['index']);
                }
            } else {
                var_dump($model->errors);
            }

        }
        return $this->render('update', ['model' => $model]);
    }
    // платежние методи ****************************************************************

    /**
     * Список платежних систем спонсора
     *
     * @param $id
     * @return string
     */
    public function actionPaymentsMethod($sponsor_id)
    {
        $filter = ColumnVisible::getColumnVisible('payments_method', [
            'payment_system_id' => 'on',
            'min_pay' => 'on',
            'fee' => 'on',
            'hold' => 'on',
            'status' => 'on',
        ]);
        $searchModel = new SponsorsPaymentsMethodSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, $sponsor_id);
        return $this->render('payments-method', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
            'filter' => $filter,
            'per_page' => Yii::$app->request->get('per-page', 20),
            'sponsor_id' => $sponsor_id,
        ]);
    }

    /**
     * Создать платежних систем спонсора
     *
     * @param $id
     * @return array|string|Response
     */
    public function actionPaymentsMethodCreate($sponsor_id)
    {
        $request = Yii::$app->request;
        $model = new SponsorPaymentsMethod();
        $model->sponsor_id = (int)$sponsor_id;

        if ($request->isAjax) {
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if ($request->isGet) {
                return [
                    'title' => "Создать метод платежа",
                    'content' => $this->renderAjax('_form-payments_method', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button('Отмена',
                            ['class' => 'btn btn-primary pull-left', 'data-dismiss' => "modal"]) .
                        Html::button('Сохранить', ['class' => 'btn btn-info', 'type' => "submit"])

                ];
            } else {
                if ($model->load($request->post()) && $model->save()) {

backend/views/post/index.php
<?php

/* @var $this yii\web\View */

/* @var $searchModel SponsorsPaymentsMethodSearch
 * @var $dataProvider ActiveDataProvider
 * @var $sponsor_id integer
 * @var $per_page integer
 * @var $filter array
 */


use backend\models\search\SponsorsPaymentsMethodSearch;
use backend\models\search\SponsorsPostSearch;
use common\models\entity\SponsorPost;
use common\models\entity\Sponsors;
use common\widgets\ColumnSetting;
use johnitvn\ajaxcrud\CrudAsset;
use kartik\form\ActiveForm;
use kartik\grid\GridView;
use yii\bootstrap\Modal;
use yii\data\ActiveDataProvider;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Посты';

CrudAsset::register($this);
?>

        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title"><?= $this->title ?></h3>

                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i
                                class="fa fa-minus"></i>
                    </button>
                    <button id="toogle-filter-btn" type="button" class="btn btn-box-tool"><i
                                class="fa fa-filter "></i></button>
                    <button type="button" class="btn btn-box-tool" data-toggle="modal"
                            data-target="#column-setting-modal"><i class="fa fa-wrench"></i></button>
                </div>
            </div>
            <div class="box-body">
                <?php $form = ActiveForm::begin(['method' => 'get', 'action' => ['']]) ?>
                <input type="hidden" id="usersearch-per-page" name="per-page" value="<?= $per_page ?>">
                <div class="row" id="filter-panel">
                    <div class="col-md-2">
                        <?= $form->field($searchModel, 'sponsor_id')
                            ->dropDownList(ArrayHelper::merge([null => 'Все'], Sponsors::getSponsorList())); ?>
                    </div>
                    <div class="col-md-2">
                        <?= $form->field($searchModel, 'post_date')->textInput(['type' => 'date']); ?>
                    </div>
                    <div class="col-md-2">
                        <?= $form->field($searchModel, 'status')->dropDownList([null => 'Все', 0 => 'Черновик', 1 => 'Опубликован']); ?>
                    </div>
                    <div class="col-md-2">
                        <?= $form->field($searchModel, 'assign_sponsor_id')->dropDownList(ArrayHelper::merge([null => 'Все'], Sponsors::getSponsorList())); ?>
                    </div>
                    <div class="col-md-2 col-md-offset-2">
                        <p style="margin-bottom: 5px;">&nbsp</p>
                        <?= Html::submitButton('Найти', ['class' => 'btn btn-warning btn-block']); ?>
                    </div>
                </div>
                <?php ActiveForm::end() ?>
                <div id="ajaxCrudDatatable">
                    <?= GridView::widget([
                        'id' => 'crud-datatable',
                        'dataProvider' => $dataProvider,
                        'filterModel' => $searchModel,
                        'rowOptions' => function ($model, $key, $index, $grid) {
                            if ($model->is_deleted) {
                                return ['style' => 'color:red'];
                            }
                            return [];
                        },
                        'pjax' => true,
                        'columns' => [
                            [
                                'attribute' => 'sponsor_id',
                                'visible' => $filter['sponsor_id'] == 'on',
                                'format' => 'raw',
                                'filter' => false,
                                'value' => function ($data) {
                                    /* @var $data SponsorsPostSearch */
                                    return Html::a($data->sponsor->name, ['/sponsors/update', 'id' => $data->sponsor_id]);
                                }
                            ],
                            [
                                'attribute' => 'post_date',
                                'visible' => $filter['post_date'] == 'on',
                                'filter' => false,
                                'format' => ['date', 'php:d.m.Y'],
                            ],
                            [
                                'attribute' => 'status',
                                'visible' => $filter['status'] == 'on',
                                'filter' => false,
                                'value' => function ($data) {
                                    return $data->status == 1 ? 'Опубликован' : 'Черновик';
                                }
                            ],
                            [
                                'attribute' => 'assign_sponsor_id',
                                'visible' => $filter['assign_sponsor_id'] == 'on',
                                'filter' => false,
                                'value' => function ($data) {
                                    /* @var $data SponsorPost */
                                    return $data->assignSponsor->name . $data->assign_site_id ? $data->assignSponsor->name : '';
                                }
                            ],
                            [
                                'attribute' => 'post',
                                'visible' => $filter['post'] == 'on',
                                'filter' => false,
                                'value' => function ($data) {
                                    return $data->post;
                                }
                            ],

                        ],

                        'striped' => true,
                        'condensed' => true,
                        'responsive' => true,
                        'panelFooterTemplate' => '<div class="kv-panel-pager" style="float: left">{pager}</div>{footer}<div class="clearfix"></div>',
                        'panel' => [
                            'heading' => '',
                            'before' => false,
                            'after' => '',
                            'footer' => '<div class="text-right" style="width: 100%"><div style="margin-top:5px">' . 'Отображать по ' .
                                Html::a(10, Url::current(['per-page' => 10]),
                                    ['class' => ($per_page == 10) ? 'btn btn-primary' : 'btn btn-default']) .
                                Html::a(20, Url::current(['per-page' => 20]),
                                    ['class' => ($per_page == 20) ? 'btn btn-primary' : 'btn btn-default']) .
                                Html::a(50, Url::current(['per-page' => 50]),
                                    ['class' => ($per_page == 50) ? 'btn btn-primary' : 'btn btn-default']) .
                                '</div></div>',
                        ],
                    ]) ?>
                </div>
            </div>
        </div>
<?php Modal::begin([
    "id" => "ajaxCrudModal",
    "footer" => "",// always need it for jquery plugin
]) ?>
<?php Modal::end(); ?>
<?= ColumnSetting::widget(['filter' => $filter, 'tableName' => 'sponsor_sites', 'model' => $searchModel]); ?>